#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+ST_WIDTH_256\
     +define+DUAL_CORE\
     +define+ST256_RANDOM_TEST_1024X128\
     -f ../filelist/filelist_st256_2c.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tsqr_mc_st256_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/tile_no    

add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/tsqr_fi       

add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c1_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st256_tb/u_tsqr_mc/c2_rtri_mem_doutb

add wave -position insertpoint /tsqr_mc_st256_tb/u_tsqr_mc/u2_hh_core/hh_din
add wave -position insertpoint /tsqr_mc_st256_tb/u_tsqr_mc/u2_hh_core/hh_dout
add wave -position insertpoint /tsqr_mc_st256_tb/u_tsqr_mc/u2_hh_core/hh0_din_rdy
add wave -position insertpoint /tsqr_mc_st256_tb/u_tsqr_mc/u2_hh_core/hh1_din_rdy
add wave -position insertpoint /tsqr_mc_st256_tb/u_tsqr_mc/u2_hh_core/hh_din_update
add wave -position insertpoint /tsqr_mc_st256_tb/u_tsqr_mc/u2_hh_core/hh_din_reg
#run 2 us                                                                            
run 2000 us                                                                            

