#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+QUAD_CORE\
     +define+ST_WIDTH_64\
     +define+ST64_RANDOM_TEST_384X32\
     -f ../filelist/filelist_st64_4c.f  
     #+define+ST64_RANDOM_TEST_256X32\
     #+define+ST64_RANDOM_TEST_384X32\
     #+define+ST64_RANDOM_TEST_512X32\

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tsqr_mc_st64_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/tile_no    

add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/tsqr_fi       

add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c1_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c2_rtri_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c3_rtri_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st64_tb/u_tsqr_mc/c4_rtri_mem_doutb
#run 2 us                                                                            
run 2000 us                                                                            

