#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+SINGLE_CORE\
     +define+ST_WIDTH_16\
     +define+ST16_RANDOM_TEST_24X8\
     -f ../filelist/filelist_st16_1c.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tsqr_mc_st16_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/tile_no    

add wave -position insertpoint sim:/tsqr_mc_st16_tb/u_tsqr_mc/hh_core/simple_dual_2/ram
add wave -position insertpoint sim:/tsqr_mc_st16_tb/u_tsqr_mc/fsms_0/*
add wave -position insertpoint sim:/tsqr_mc_st16_tb/u_tsqr_mc/hh_core/*
add wave -position insertpoint sim:/tsqr_mc_st16_tb/u_tsqr_mc/hh_core/u_hh_datapath/*

add wave -position insertpoint sim:/tsqr_mc_st16_tb/u_tsqr_mc/hh_core/u_hh_datapath/hh_datapath_1/FP_DDOT_dp/*
add wave -position insertpoint sim:/tsqr_mc_st16_tb/u_tsqr_mc/hh_core/u_hh_datapath/hh_datapath_1/axpy_dp/*
#run 2 us                                                                            
run 2000 us                                                                            

