#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+EIGHT_CORE\
     +define+ST_WIDTH_16\
     +define+ST16_RANDOM_TEST_1024X8\
     -f ../filelist/filelist_st16_8c.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tsqr_mc_st16_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/tile_no    

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/clk        
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/rst        
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_tsqr_en    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_tile_no    
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_hh_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_mx_cnt     
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_mem0_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_mem1_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_tsqr_fi       
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/tsqr_fi       

#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/hh_din
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr2_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d1
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr2_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr3_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d2
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/u_sqrt/io_in_a
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/u_sqrt/io_out_s
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr3_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr5_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/vk1
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr5_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr6_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d3
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr6_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr7_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/tk
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr7_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr9_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d4
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr9_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr10_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/d5
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr10_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr11_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/hh_dout
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr11_vld
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_fsm/hqr8_rdy
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/yj0
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/yj1
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/yj2
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/yj3
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/yj4
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/yj5
#add wave -position insertpoint /tsqr_mc_st16_tb/u_tsqr_mc/u1_hh_core/u_hh_datapath/hh_din

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c1_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c2_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c3_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c4_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c5_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c6_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c7_rtri_mem_doutb

add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx0_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx0_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx0_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx0_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx0_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx0_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx0_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx1_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx1_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx1_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx1_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx1_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx1_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_dmx1_mem_doutb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_rtri_mem_ena  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_rtri_mem_wea  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_rtri_mem_addra
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_rtri_mem_dina 
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_rtri_mem_enb  
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_rtri_mem_addrb
add wave -noupdate -format logic -unsigned tsqr_mc_st16_tb/u_tsqr_mc/c8_rtri_mem_doutb
#run 2 us                                                                            
run 2000 us                                                                            

